environment:
  matrix:
  # 32-bit (x86) Windows build (VS 2015):
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VC_GENERATOR: "Visual Studio 14 2015"
    VC_TOOLCHAIN: v140_xp
    VC_TARGET_PLATFORMNAME: Win32
    OUTPUT_PLATFORMNAME: vs14-x86
    FILEVERSION_TO_CHECK: vcruntime140.dll
  # 32-bit (x86) Windows build (VS 2017):
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VC_GENERATOR: "Visual Studio 15 2017"
    VC_TOOLCHAIN: v141_xp
    VC_TARGET_PLATFORMNAME: Win32
    OUTPUT_PLATFORMNAME: vs15-x86
    FILEVERSION_TO_CHECK: vcruntime140.dll
  # 64-bit (x64) Windows build (VS 2017):
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VC_GENERATOR: "Visual Studio 15 2017"
    VC_TOOLCHAIN: v141_xp
    VC_TARGET_PLATFORMNAME: x64
    OUTPUT_PLATFORMNAME: vs15-x64
    FILEVERSION_TO_CHECK: vcruntime140.dll
  # 32-bit (x86) Windows build (VS 2019):
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VC_GENERATOR: "Visual Studio 16 2019"
    VC_TOOLCHAIN: v142
    VC_TARGET_PLATFORMNAME: Win32
    OUTPUT_PLATFORMNAME: vs16-x86
    FILEVERSION_TO_CHECK: vcruntime140.dll
  # 64-bit (x64) Windows build (VS 2019):
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VC_GENERATOR: "Visual Studio 16 2019"
    VC_TOOLCHAIN: v142
    VC_TARGET_PLATFORMNAME: x64
    OUTPUT_PLATFORMNAME: vs16-x64
    FILEVERSION_TO_CHECK: vcruntime140.dll

platform:
  - x64

configuration:
  - Release

before_build:
  # Use CMake to configure the appropriate Visual Studio (MSBUILD) generator, toolchain, target platform, and install location
  - cmake -H. -Bbuild  -G "%VC_GENERATOR%" -T "%VC_TOOLCHAIN%" -A "%VC_TARGET_PLATFORMNAME%" -DCMAKE_INSTALL_PREFIX:PATH="%APPVEYOR_BUILD_FOLDER%\install"

build:
  parallel: true
  project: build/INSTALL.vcxproj

after_build:
  # Package the install output into a zip
  # Name the zip file based on the platform-name & repo info:
  #   applocalconfig-<BRANCH>-<DATE>-<TIME>-<COMMIT_FIRST_7>-<PLATFORM: x86, x64>-<RUNTIME_VERSION>.zip
  - ps: |
      $VersionInfo = (Get-Item "$($env:APPVEYOR_BUILD_FOLDER)\install\$($env:FILEVERSION_TO_CHECK)").VersionInfo
      $FileVersion = ("{0}.{1}.{2}.{3}" -f $VersionInfo.FileMajorPart, $VersionInfo.FileMinorPart,$VersionInfo.FileBuildPart, $VersionInfo.FilePrivatePart)
      cmd /c 7z a "applocalconfig-$($env:APPVEYOR_REPO_BRANCH)-$(get-date -f yyyyMMdd-HHmmss)-$($env:APPVEYOR_REPO_COMMIT.SubString(0,7))-$($env:OUTPUT_PLATFORMNAME)-$($FileVersion).zip" "$($env:APPVEYOR_BUILD_FOLDER)\install\*"

artifacts:
  - path: applocalconfig-*.zip
    name: AppLocalConfig (zip)
